linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - varcheck
    - gocyclo
    - unused
    - gocritic
    - rowserrcheck
    - sqlclosecheck
    - prealloc