version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: build/docker/Dockerfile
      args:
        app: api
    env_file:
      - .env
    ports:
      - "8000:8000"
    healthcheck:
      test: nc -z localhost 8000 || exit -1
      interval: 10s
      timeout: 5s
      retries: 3